#!/bin/bash
# rotate-incidents.sh - Monthly rotation of MEMORY.md incidents section
# Cron: 0 2 1 * * (2 AM on 1st of month)

set -euo pipefail

WORKSPACE="${WORKSPACE_DIR:-$HOME/.openclaw/workspace-chappie}"
MEMORY_FILE="$WORKSPACE/MEMORY.md"
INCIDENTS_DIR="$WORKSPACE/memory/incidents"
LOG_FILE="$WORKSPACE/memory/.rotation.log"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "=== Starting monthly incident rotation ==="

# Check if MEMORY.md exists
if [[ ! -f "$MEMORY_FILE" ]]; then
    log "MEMORY.md not found. Skipping rotation."
    exit 0
fi

# Extract incidents section
INCIDENTS_START=$(grep -n "## Incidents" "$MEMORY_FILE" | cut -d: -f1 || echo "0")

if [[ "$INCIDENTS_START" == "0" ]]; then
    log "No '## Incidents' section found. Skipping rotation."
    exit 0
fi

# Find next section or end of file
NEXT_SECTION=$(tail -n +$((INCIDENTS_START + 1)) "$MEMORY_FILE" | grep -n "^## " | head -1 | cut -d: -f1 || echo "999999")

if [[ "$NEXT_SECTION" != "999999" ]]; then
    INCIDENTS_END=$((INCIDENTS_START + NEXT_SECTION))
else
    INCIDENTS_END=$(wc -l < "$MEMORY_FILE")
fi

# Extract incidents content
INCIDENTS_CONTENT=$(sed -n "${INCIDENTS_START},${INCIDENTS_END}p" "$MEMORY_FILE")

# Get previous month for archive filename
PREV_MONTH=$(date -d "last month" '+%Y-%m')
ARCHIVE_FILE="$INCIDENTS_DIR/$PREV_MONTH.md"

# Create archive
mkdir -p "$INCIDENTS_DIR"

cat > "$ARCHIVE_FILE" << EOF
# Incidents Archive - $PREV_MONTH
**Archived:** $(date '+%Y-%m-%d')

$INCIDENTS_CONTENT

---
**Note:** This archive was auto-generated by rotate-incidents.sh
EOF

log "Archived incidents to: $ARCHIVE_FILE ($(wc -l < "$ARCHIVE_FILE") lines)"

# Replace incidents section in MEMORY.md with current month header
CURRENT_MONTH=$(date '+%Y-%m')
TEMP_FILE=$(mktemp)

{
    head -n $((INCIDENTS_START - 1)) "$MEMORY_FILE"
    cat << EOF
## Incidents (Current Month: $CURRENT_MONTH)
<!-- Auto-rotated on 1st of each month. See memory/incidents/ for archives -->

- **$(date '+%Y-%m-%d'):** [No incidents this month yet]

EOF
    tail -n +$((INCIDENTS_END + 1)) "$MEMORY_FILE"
} > "$TEMP_FILE"

# Replace original file
cp "$TEMP_FILE" "$MEMORY_FILE"
rm "$TEMP_FILE"

# Update size tag
SIZE_KB=$(du -k "$MEMORY_FILE" | cut -f1)
SIZE_BYTES=$(stat -f%z "$MEMORY_FILE" 2>/dev/null || stat -c%s "$MEMORY_FILE")
SIZE_KB_FLOAT=$(echo "scale=1; $SIZE_BYTES / 1024" | bc)

log "Updated MEMORY.md (new size: ${SIZE_KB_FLOAT}KB)"

# Commit changes if git repo
if [[ -d "$WORKSPACE/.git" ]]; then
    cd "$WORKSPACE"
    git add "$MEMORY_FILE" "$ARCHIVE_FILE"
    git commit -m "chore: rotate incidents archive ($PREV_MONTH) - auto-generated" || log "No changes to commit"
fi

log "=== Rotation complete ==="

# Optional: Post to Kanban if configured
if command -v openclaw &>/dev/null; then
    openclaw message agent:pm:telegram:default:direct:1074136117 \
        "🔄 **Monthly Rotation Complete**\n\nArchived incidents from $PREV_MONTH to \`memory/incidents/$PREV_MONTH.md\`\nMEMORY.md size: ${SIZE_KB_FLOAT}KB" \
        2>/dev/null || log "Could not send notification"
fi

exit 0
